stages:
    - test

phpUnit:
    stage: test
    script:
        - vendor/bin/phpunit

easyCodingStandards:
    stage: test
    script:
        - 'vendor/bin/ecs check --ansi'

phpStan:
    stage: test
    script:
        - 'vendor/bin/phpstan analyse --ansi'
