stages:
    - install
    - test
    - build

install:
    stage: install
    script:
        - 'composer verify'
        - 'composer install'

phpunit_jobs:
    stage: test
    script:
        - 'vendor/bin/phpunit --testsuite main'

ecs_jobs:
    stage: test
    script:
        - 'composer check-cs src'
        - 'composer check-cs src -- --fix'
