name: 'Travis CI'
language: php
php: ^7.2
install:
    - 'composer update --prefer-source $COMPOSER_FLAGS'
test:
    name: PhpUnit
    php: ^7.2
    script:
        - 'vendor/bin/phpunit --testsuite main'
cache:
    directories:
        - $HOME/.composer/cache
notifications:
    email: false
