language: php

install:
    - 'composer install'

jobs:
    include:
        -
            stage: test
            php: '7.2'
            script:
                - 'vendor/bin/phpunit --testsuite main'
        -
            stage: test
            php: '7.3'
            script:
                - 'vendor/bin/phpunit --testsuite main'
        -
            stage: test
            php: '7.4'
            script:
                - 'vendor/bin/phpunit --testsuite main'

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
