language: php

install:
    - composer install

# phpunit is run by default, skip it
script: skip

jobs:
    include:
        -
            stage: test
            php: 7.2
            name: Run bin
            script:
                - bin/CIConfigGen.php
                - bin/CIConfigGen.php craft:generate composer.json

        -
            stage: test
            php: 7.2
            name: "Coding Standards"
            script:
                - composer check-cs
        -

            stage: test
            php: 7.2
            name: "Tests"
            script:
                - vendor/bin/phpunit

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email:
        on_success: never
