language: php

php:
    - '7.2'
    - '7.3'
    - '7.4'

install:
    - composer install

jobs:
    include:
        -
            stage: test
            name: Run bin
            script:
                - bin/CIConfigGen.php

        -
            stage: test
            name: Run Command
            script:
                - bin/CIConfigGen.php gc:WhatTime

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email:
        on_success: never