services:
    _defaults:
        public: true
        autowire: true

    App\:
        resource: "../src"
        exclude:
            - "../src/HttpKernel/ApplicationKernel.php"
            - "../src/Intermediary/IntermediaryGenerateObject.php"

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    # composer json factory
    Symplify\MonorepoBuilder\ComposerJsonObject\ComposerJsonFactory: null
    Symplify\MonorepoBuilder\FileSystem\JsonFileManager:
        arguments:
            $inlineSections: []

    Symfony\Component\Filesystem\Filesystem: null
