name: 'Github Actions Yaml'
'on': push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: 'Checkout Repository'
                uses: actions/checkout@v1
            -
                name: 'Run composer install'
                run: 'composer install --prefer-dist'
            -
                name: test-0
                run: bin/phpunit
            -
                name: test-1
                run: bin/phpunit
            -
                name: test-2
                run: bin/phpunit
            -
                name: ECS
                run: bin/phpunit
